###########################
#Thesis: Packages
###########################

library(ggplot2)
library(dplyr)
library(readxl)
library(lubridate)
library(gdata)
library(ggfortify)
library(zoo)
library(xts)
library(tseries)
library(astsa)
library(forecast)
library(TSstudio)
library(feasts)
library(tsibble)
library(patchwork)
library(e1071)
library(keras)
library(tensorflow)
library(moments)
library(ggpp)
library(urca)
library(caret)
library(greybox)
library(rsample)
library(rugarch)
library(FinTS)
library(xtable)
library(Metrics)
library(tfruns)
library(TTR)

